### ISSUE TITLE
undefined: tls.RenegotiateFreelyAsClient

### ISSUE THREAD

**Issue by salcedogeiner** [lib/pq#562]
I cant run a go get or with beggoo 'bee run', appear it:

`# github.com/lib/pq
../github.com/lib/pq/ssl_go1.7.go:13: conf.Renegotiation undefined (type *tls.Config has no field or method Renegotiation)
../github.com/lib/pq/ssl_go1.7.go:13: undefined: tls.RenegotiateFreelyAsClient`

**Comment by cbandy** [comment]
What version of Go are you running?

That file has a [build flag](https://github.com/lib/pq/blob/0477eb88c5ca4009cb281f13c90633375b6a9987/ssl_go1.7.go#L1) which should something something versions of Go older than 1.7.

```go
// +build go1.7
```

**Comment by salcedogeiner** [comment]
last version of go

**Comment by mjibson** [comment]
What is the output of `go version`?

**Comment by salcedogeiner** [comment]
go version go1.7.1 linux/amd64

**Comment by tamird** [comment]
does `go get -u github.com/lib/pq` work? if no, what error does it produce?

Also, what is the output of `bee version`?

**Comment by salcedogeiner** [comment]
go get dont work with go 1.7.1, and bee version is 1.7.2,

i was reinstalled golang to version 1.6.4 and it work

**Comment by tamird** [comment]
Well, that's not surprising, since the offending code has a build tag that prevents it from compiling in Go versions less than 1.7.

Can you please list the full output of both `go version` and `bee version`?

**Comment by salcedogeiner** [comment]
├── Beego     : 1.7.2
├── GoVersion : go1.7.1

**Comment by mjibson** [comment]
The only conclusion I can come to is that something about your installation is not correct. Maybe your package manager did something unexpected, or you have some old files around. Not sure. But so far I'm not convinced this is a problem with lib/pq. My current suggestion is to completely remove go from your machine and reinstall by downloading the files manually from golang.org/dl.

**Comment by cbandy** [comment]
I double-checked that `tls.Config. Renegotiation` and `tls.RenegotiateFreelyAsClient` were added to Go 1.7 at the same time: https://github.com/golang/go/commit/af125a5193c75dd59307fcf1b26d885010ce8bfd

**Comment by rail-ka** [comment]
I couldn't build project after go updating 1.8 (brew) in MacOS:
```
# github.com/lib/pq
../../github.com/lib/pq/conn_go18.go:11: undefined: driver.NamedValue
../../github.com/lib/pq/conn_go18.go:29: undefined: driver.NamedValue
../../github.com/lib/pq/conn_go18.go:44: undefined: driver.TxOptions
```
I tried to update `go get -u github.com/lib/pq`, but it does not help

**Comment by mjibson** [comment]
I think there is still something broken about your go installation. No one else has been able to replicate your report.

**Comment by tejasmanohar** [comment]
Yep, something's definitely broken with your Go installation. Since you're using brew (which I don't advise for Go), check $GOROOT.
