### ISSUE TITLE
lib\pq\notify.go:787: undefined: time.Until

### ISSUE THREAD

**Issue by Bobsar0** [lib/pq#741]
Line 787 in file 'notify.go' lists: 	time.Sleep(time.Until(nextReconnect)).
However, there is no function or method 'Until' defined in the time package.
Correct me if I'm wrong please.

**Comment by peterstace** [comment]
This one? https://golang.org/pkg/time/#Until

**Comment by praveenmenon** [comment]
I am facing the same issue. I have go 1.7.0 and i cannot upgrade to the newer version. I am facing issue when installing goose migration package. What do i do to fix this?

**Comment by mjibson** [comment]
lib/pq recently bumped its minimum supported Go version to 1.8 (https://github.com/lib/pq/commit/b75c1328e7ddc1fe2897547419e47bbb1f2ce736). If you want to keep using lib/pq on Go 1.7 or below you will have to pin your lib/pq version to before that commit.

**Comment by Bobsar0** [comment]
Oh ok just needed to upgrade my Go version. Thanks @peterstace and @mjibson.

**Comment by tmagilldotcom** [comment]
I am still receiving this error, i have Go version 1.10

**Comment by mjibson** [comment]
Maybe your GOPATH, GOROOT, or something else is messed up. It's definitely a go version problem.

**Comment by tmagilldotcom** [comment]
It doesn't work with version 1.10, reverting it back to 1.8 worked...

**Comment by tmagilldotcom** [comment]
It doesn't work with version 1.10, reverting it back to 1.8 worked...

**Comment by msoulier** [comment]
So, if I'm stuck on an old version of Go, how am I supposed to know that lib/pq is no longer compatible with my version, beyond compile failures? Is there no way to publish this in a way that the go get command would understand?
