### ISSUE TITLE
[Help Wanted] undefined: driver.Connector

### ISSUE THREAD

**Issue by fwhezfwhez** [lib/pq#991]
In my project, go 1.9, 
this package will throw `undefined: driver.Connector`.

We use it to run  production appliction and for some reason, can't upgrade go version.

Thus, how to solve this problem.

**Comment by mjibson** [comment]
lib/pq supports the current and previous Go versions. If you want something that works with 1.9 you need to pin your dependency to an older version of lib/pq.
